name: Deploy On Release

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:

  tests-and-coverage:
    name: Test & Coverage
    uses: ./.github/workflows/reusable_test.yml
    with:
      use_latest_pytorch_gpytorch: false
    secrets: inherit

  package-deploy-pypi:
    name: Package and deploy to pypi.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for PyPI OIDC authentication.
    env:
      # `uv pip ...` requires venv by default. This skips that requirement.
      UV_SYSTEM_PYTHON: 1
    needs: tests-and-coverage
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        uv pip install .[test]
        uv pip install --upgrade build setuptools setuptools_scm wheel
    - name: Build packages (wheel and source distribution)
      run: |
        python -m build --sdist --wheel
    - name: Verify packages
      run: |
        ./scripts/verify_py_packages.sh
    - name: Deploy to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true

  version-and-publish-website:
    needs: package-deploy-pypi
    name: Version and Publish website
    uses: ./.github/workflows/publish_website.yml
    with:
      new_version: ${{ github.event.release.tag_name }}
    permissions:
      pages: write
      id-token: write
      contents: write
